apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a-name-that-is-enticing
  description: A description
  tags:
    - go
    - website

spec: 
  type: service
  lifecycle: production
  owner: our-team
